"""add tenant access_code_hash

Revision ID: e2cfe43da955
Revises: d1d0b376db08
Create Date: 2026-09-07 05:39:37.369954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cfe43da955'
down_revision: Union[str, Sequence[str], None] = 'd1d0b376db08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('access_code_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'access_code_hash')
    # ### end Alembic commands ###
